PipelineSecrets:
  DockerConfig: '{"auths": {"docker-registry.default.svc:5000": {"auth": "c2VydmljZWFjY291bnQ6ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklpSjkuZXlKcGMzTWlPaUpyZFdKbGNtNWxkR1Z6TDNObGNuWnBZMlZoWTJOdmRXNTBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5dVlXMWxjM0JoWTJVaU9pSnFlQ0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVmpjbVYwTG01aGJXVWlPaUpxWlc1cmFXNXpMWGd0Y21WbmFYTjBjbmt0ZEc5clpXNHRibnB5WW5vaUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sY25acFkyVXRZV05qYjNWdWRDNXVZVzFsSWpvaWFtVnVhMmx1Y3kxNExYSmxaMmx6ZEhKNUlpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVkV2xrSWpvaU5tSXhZV1ZsTXpBdE1qaGxZeTB4TVdVNUxUazFPVFV0WWpRNU9XSmhZakF5TmpRMElpd2ljM1ZpSWpvaWMzbHpkR1Z0T25ObGNuWnBZMlZoWTJOdmRXNTBPbXA0T21wbGJtdHBibk10ZUMxeVpXZHBjM1J5ZVNKOS5Cd08weUZ1SzR3alBUVkdsU3ljekJBbHZaVU9BMllYQ3hTMXVYaE1SLXE5eGlWT0U1d01tQ0g4MUV2RF82ODN5eV9xamFCNnVJV3o0VmRoOXBfWEJMXzJQOWs0QVRhbl9kNC1qbDVLZWlNd3RWZ0N2aFBuWVVSYUUzSmhKaE9JVTlEeWlJQ2FfQTFqRXpGNWZpZFdHaFpBaTZzMDBCMk1RWGhIX2F3VkxBanM5cGNqQ1NTanhRMmhDa194Nld2M3EzdWQ5MTc1QjFZWi1iUEVfcWN2VFpFWkZ1UU9ZVjgzVmtwaUdzdVhEUXBBV3ItbTdhWVVZd2xtU2RqckhSRlpfTnNsRUNZUmpONnp0WkpXR1g3Y1F0ZnQ1MzdhVU5DM015Z3JIOXRaVjUyZDJBSGIzTjJ4X0VINld6Z0lDMDlkTjc2RzBIdXVERUJLSmNKbVdRYkpZTmc="}}}'
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
controllerbuild:
  enabled: true
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: cpd.techsur.solutions
    exposer: Route
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: docker-registry.default.svc:5000
        TILLER_NAMESPACE: kube-system
  enabled: false
prow: {}
